/** Host RPC channels implemented by the Jet TypeScript host-server (non-agent). */
export const HOST_CHANNELS = new Set([
  "fs:readFile",
  "fs:writeFile",
  "fs:writeTempDrop",
  "fs:readDir",
  "fs:stat",
  "fs:showOpenFolderDialog",
  "fs:showSaveFileDialog",
  "git:isRepo",
  "git:status",
  "git:diff",
  "git:branch",
  "git:summary",
  "git:branches",
  "git:stage",
  "git:unstage",
  "git:discard",
  "git:commit",
  "git:checkout",
  "git:fetch",
  "git:pull",
  "git:push",
  "git:history",
  "search:listFiles",
  "search:project",
  "search:fileSearch",
  "search:trackFileAccess",
  "search:isScanReady",
  "search:isSupported",
  "workspace:activate",
  "workspace:deactivate",
  "lsp:start",
  "lsp:stop",
  "terminal:create",
  "terminal:write",
  "terminal:writeBinary",
  "terminal:resize",
  "terminal:attach",
  "terminal:dispose",
  "tasks:spawn",
  "perf:recordStartup",
  "perf:getStartupLogPath",
  "gharargah:getLaunchConfig",
  "gharargah:getHomeDir",
  "gharargah:loadGlobalGharargahrcScanRoots",
  "ui:syncNativeChrome",
])

/** @deprecated Use HOST_CHANNELS */
export const RUST_HOST_CHANNELS = HOST_CHANNELS
