// AUTO-GENERATED by scripts/generate-default-keybindings.mjs — override via keymaps.registerUser([bind(...)]).
import { anyOverlayOpen, type KeymapContext } from "./context-keys.js"
import { bind, type JetKeyBinding } from "./keymaps.js"
import type { JetCommands } from "./jet-commands.js"

const noOverlay = (ctx: KeymapContext) => !anyOverlayOpen(ctx)
const editorFocus = (ctx: KeymapContext) => ctx.editorFocus && noOverlay(ctx)
const workspaceOpen = (ctx: KeymapContext) => ctx.workspaceOpen && noOverlay(ctx)
const listFocus = (ctx: KeymapContext) => ctx.listFocus && noOverlay(ctx)

export function createDefaultKeybindings(cmd: JetCommands): JetKeyBinding[] {
  return [
  bind("Cmd-n", cmd.newFile, workspaceOpen),
  bind("Cmd-p", cmd.quickOpen, noOverlay),
  bind("Cmd-Shift-p", cmd.palette, noOverlay),
  bind("Cmd-Shift-b", cmd.bufferList, workspaceOpen),
  bind("Cmd-k Cmd-f", cmd.quickOpen, workspaceOpen),
  bind("Cmd-k Cmd-s", cmd.locationListSearch, workspaceOpen),
  bind("Cmd-k Cmd-w", cmd.focusSidebar, workspaceOpen),
  bind("Cmd-s", cmd.save, workspaceOpen),
  bind("Cmd-o", cmd.openFile, noOverlay),
  bind("Cmd-k Cmd-o", cmd.openFolder, noOverlay),
  bind("Cmd-w", cmd.closeBuffer, workspaceOpen),
  bind("Cmd-f", cmd.find, editorFocus),
  bind("Cmd-Alt-f", cmd.replace, editorFocus),
  bind("Ctrl-g", cmd.gotoLine, editorFocus),
  bind("Cmd-Shift-f", cmd.locationListSearch, workspaceOpen),
  bind("Cmd-Shift-e", cmd.explorer, workspaceOpen),
  bind("Cmd-Shift-m", cmd.locationListProblems, workspaceOpen),
  bind("Alt-j", cmd.jumpBack, workspaceOpen),
  bind("Alt-Shift-j", cmd.jumpForward, workspaceOpen),

  bind("Cmd-/", cmd.toggleComment, editorFocus),
  bind("Shift-Alt-ArrowUp", cmd.copyLineUp, editorFocus),
  bind("Shift-Alt-ArrowDown", cmd.copyLineDown, editorFocus),
  bind("Alt-ArrowUp", cmd.moveLineUp, editorFocus),
  bind("Alt-ArrowDown", cmd.moveLineDown, editorFocus),
  bind("Cmd-Alt-ArrowUp", cmd.addCursorAbove, editorFocus),
  bind("Cmd-Alt-ArrowDown", cmd.addCursorBelow, editorFocus),
  bind("Ctrl-Shift-ArrowUp", cmd.addCursorAbove, editorFocus),
  bind("Ctrl-Shift-ArrowDown", cmd.addCursorBelow, editorFocus),
  bind("Cmd-d", cmd.selectNextOccurrence, editorFocus),
  bind("Cmd-k Cmd-d", cmd.skipNextOccurrence, editorFocus),
  bind("Cmd-Shift-l", cmd.selectAllOccurrences, editorFocus),
  bind("Ctrl-Cmd-g", cmd.selectAllOccurrences, editorFocus),
  bind("Cmd-l", cmd.expandLineSelection, editorFocus),
  bind("Cmd-Shift-\\", cmd.jumpToBracket, editorFocus),
  bind("Cmd-]", cmd.indentMore, editorFocus),
  bind("Cmd-[", cmd.indentLess, editorFocus),
  bind("Cmd-z", cmd.undo, editorFocus),
  bind("Cmd-Shift-z", cmd.redo, editorFocus),
  bind("Cmd-y", cmd.redo, editorFocus),
  bind("Cmd-u", cmd.cursorUndo, editorFocus),
  bind("Shift-Alt-ArrowRight", cmd.smartSelectExpand, editorFocus),
  bind("Shift-Alt-ArrowLeft", cmd.smartSelectShrink, editorFocus),

  bind("Cmd-Shift-]", cmd.nextBuffer, workspaceOpen),
  bind("Cmd-Shift-[", cmd.prevBuffer, workspaceOpen),
  bind("Cmd-0", cmd.focusSidebar, workspaceOpen),
  bind("Cmd-1", cmd.focusEditorGroup, workspaceOpen),
  bind("Cmd-9", cmd.lastEditorGroup, workspaceOpen),
  bind("Cmd-k ArrowRight", cmd.splitEditorRight, workspaceOpen),
  bind("Cmd-Alt-0", cmd.toggleEditorLayout, workspaceOpen),
  bind("Cmd-=", cmd.zoomIn, noOverlay),
  bind("Cmd--", cmd.zoomOut, noOverlay),
  bind("Escape", cmd.closeQuickOpen, ctx => anyOverlayOpen(ctx)),

  bind("F1", cmd.palette, noOverlay),
  bind("Cmd-Shift-o", cmd.quickOutline, editorFocus),
  bind("Shift-Alt-f", cmd.formatDocument, editorFocus),
  bind("F2", cmd.rename, editorFocus),
  bind("F12", cmd.goToDefinition, editorFocus),
  bind("Shift-F12", cmd.goToReferences, editorFocus),
  bind("Ctrl-Space", cmd.triggerSuggest, editorFocus),
  bind("Cmd-Shift-Space", cmd.triggerParameterHints, editorFocus),
  bind("Cmd-.", cmd.quickFix, editorFocus),
  bind("Cmd-F12", cmd.goToImplementation, editorFocus),

  bind("ArrowDown", cmd.listFocusNext, listFocus),
  bind("ArrowUp", cmd.listFocusPrev, listFocus),
  bind("Enter", cmd.listFocusActivate, listFocus),
  bind("PageUp", cmd.listFocusPageUp, listFocus),
  bind("PageDown", cmd.listFocusPageDown, listFocus),
  bind("Home", cmd.listFocusFirst, listFocus),
  bind("End", cmd.listFocusLast, listFocus),
  ]
}
