// AUTO-GENERATED by scripts/generate-default-keybindings.mjs — override via keymaps.registerUser([bind(...)]).
import { anyOverlayOpen, type KeymapContext } from "./context-keys.js"
import { bind, type JetKeyBinding } from "./keymaps.js"
import type { JetCommands } from "./jet-commands.js"

const noOverlay = (ctx: KeymapContext) => !anyOverlayOpen(ctx)
const editorFocus = (ctx: KeymapContext) => ctx.editorFocus && noOverlay(ctx)
const workspaceOpen = (ctx: KeymapContext) => ctx.workspaceOpen && noOverlay(ctx)
const listFocus = (ctx: KeymapContext) => ctx.listFocus && noOverlay(ctx)

export function createDefaultKeybindings(cmd: JetCommands): JetKeyBinding[] {
  return [
  // --- App shell ---
  bind("Cmd-n", cmd.newFile, workspaceOpen),
  bind("Cmd-p", cmd.quickOpen, workspaceOpen),
  bind("Cmd-Shift-p", cmd.palette, noOverlay),
  bind("Cmd-s", cmd.save, workspaceOpen),
  bind("Cmd-o", cmd.openFile, noOverlay),
  bind("Cmd-k Cmd-o", cmd.openFolder, noOverlay),
  bind("Cmd-w", cmd.closeTab, workspaceOpen),
  bind("Cmd-f", cmd.find, editorFocus),
  bind("Cmd-Alt-f", cmd.replace, editorFocus),
  bind("Ctrl-g", cmd.gotoLine, editorFocus),
  bind("Cmd-Shift-f", cmd.search, workspaceOpen),
  bind("Ctrl-Shift-g", cmd.git, workspaceOpen),
  bind("Cmd-Shift-e", cmd.explorer, workspaceOpen),
  bind("Ctrl-`", cmd.terminal, workspaceOpen),
  bind("Cmd-Shift-m", cmd.problems, workspaceOpen),

  // --- Tier 1: Editor commands ---
  bind("Cmd-/", cmd.toggleComment, editorFocus),
  bind("Shift-Alt-ArrowUp", cmd.copyLineUp, editorFocus),
  bind("Shift-Alt-ArrowDown", cmd.copyLineDown, editorFocus),
  bind("Alt-ArrowUp", cmd.moveLineUp, editorFocus),
  bind("Alt-ArrowDown", cmd.moveLineDown, editorFocus),
  bind("Cmd-Alt-ArrowUp", cmd.addCursorAbove, editorFocus),
  bind("Cmd-Alt-ArrowDown", cmd.addCursorBelow, editorFocus),
  bind("Cmd-d", cmd.selectNextOccurrence, editorFocus),
  bind("Cmd-Shift-l", cmd.selectAllOccurrences, editorFocus),
  bind("Cmd-l", cmd.expandLineSelection, editorFocus),
  bind("Cmd-Shift-\\", cmd.jumpToBracket, editorFocus),
  bind("Cmd-]", cmd.indentMore, editorFocus),
  bind("Cmd-[", cmd.indentLess, editorFocus),
  bind("Cmd-z", cmd.undo, editorFocus),
  bind("Cmd-Shift-z", cmd.redo, editorFocus),
  bind("Cmd-y", cmd.redo, editorFocus),
  bind("Cmd-u", cmd.cursorUndo, editorFocus),
  bind("Shift-Alt-ArrowRight", cmd.smartSelectExpand, editorFocus),
  bind("Shift-Alt-ArrowLeft", cmd.smartSelectShrink, editorFocus),

  // --- Tier 2: Window / Layout ---
  bind("Cmd-Shift-]", cmd.nextEditor, workspaceOpen),
  bind("Cmd-Shift-[", cmd.prevEditor, workspaceOpen),
  bind("Cmd-Alt-ArrowRight", cmd.nextEditor, workspaceOpen),
  bind("Cmd-Alt-ArrowLeft", cmd.prevEditor, workspaceOpen),
  bind("Cmd-k w", cmd.closeAllTabs, workspaceOpen),
  bind("Cmd-0", cmd.focusSidebar, workspaceOpen),
  bind("Cmd-1", cmd.focusEditorGroup, workspaceOpen),
  bind("Cmd-9", cmd.lastEditorGroup, workspaceOpen),
  bind("Cmd-k ArrowRight", cmd.splitEditorRight, workspaceOpen),
  bind("Cmd-Alt-0", cmd.toggleEditorLayout, workspaceOpen),
  bind("Cmd-=", cmd.zoomIn, noOverlay),
  bind("Cmd--", cmd.zoomOut, noOverlay),
  bind("Cmd-Shift-=", cmd.zoomIn, noOverlay),
  bind("Cmd-Shift--", cmd.zoomOut, noOverlay),
  bind("Escape", cmd.closeQuickOpen, ctx => anyOverlayOpen(ctx)),

  // --- Tier 3: Palette entry points ---
  bind("F1", cmd.palette, noOverlay),
  bind("Cmd-Shift-o", cmd.quickOutline, editorFocus),
  bind("Shift-Alt-f", cmd.formatDocument, editorFocus),
  bind("F2", cmd.rename, editorFocus),
  bind("Shift-F12", cmd.goToReferences, editorFocus),

  // --- Tier 4: List navigation (non-conflicting keys only) ---
  bind("PageUp", cmd.listFocusPageUp, listFocus),
  bind("PageDown", cmd.listFocusPageDown, listFocus),
  bind("Home", cmd.listFocusFirst, listFocus),
  bind("End", cmd.listFocusLast, listFocus),

  // --- Git chords (stubs) ---
  bind("Cmd-k Cmd-r", cmd.gitRevertSelected, workspaceOpen),
  bind("Cmd-k Cmd-Alt-s", cmd.gitStageSelected, workspaceOpen),
  bind("Cmd-k Cmd-n", cmd.gitUnstageSelected, workspaceOpen),
  ]
}
