export { createHostRegistry, createDefaultSidecarServices } from "./register-all.js"
export { wireRegistryToElectron, bindElectronRenderer } from "./electron-bridge.js"
export { startHostHttpServer } from "./http-server.js"
export { sendToRenderer, registerHostRenderer, unregisterHostRenderer } from "./host-renderer.js"
export { stopAllLsp } from "./lsp-bridge.js"
export { stopAllTerminals, disposeTerminalsForClient } from "./terminal.js"
export { stopWorkspaceHost } from "./workspace-host.js"
export { stopAllBackgroundWorkers, prewarmBackgroundWorkers } from "./background-pool.js"
export type { HostServices, HostDialogProvider, HostLaunchState } from "./services.js"
export { HostRegistry } from "./registry.js"
