export { PanelDock } from "./dock/index.js"
export { CommandPalette } from "./components/CommandPalette.js"
export { PaletteOverlay } from "./components/PaletteOverlay.js"
export { StatusBar } from "./status/StatusBar.js"
export { WelcomeView } from "./welcome/WelcomeView.js"
export { EditorTabHost, getEditorView } from "./tabs/EditorTabHost.js"
export { ExplorerTab } from "./tabs/ExplorerTab.js"
export { GitTab } from "./tabs/GitTab.js"
export { SearchTab } from "./tabs/SearchTab.js"
export { ProblemsTab } from "./tabs/ProblemsTab.js"
export { TerminalTab } from "./tabs/TerminalTab.js"
export { bundledThemes, defaultJetTheme, applyJetThemeCss } from "./theme/bundled.js"
export { jetMotion } from "./motion/tokens.js"
export { cn } from "./lib/utils.js"
