import type { GharargahTheme } from "@gharargah/codemirror"
import {
  makeTheme,
  paletteAnsi,
  paletteColors,
  paletteHighlights,
  type ColorScheme,
} from "./theme-palette.js"
import { radDebuggerThemeList, radDebuggerThemes } from "./raddebugger.js"
import { glassThemeList, glassThemes } from "./glass.js"

export type { ColorScheme } from "./theme-palette.js"

export const defaultThemeId = "ayu-dark"

const ayuSource = "https://github.com/ayu-theme/ayu-colors"
const everforestSource = "https://raw.githubusercontent.com/sainnhe/everforest/master/palette.md"
const gruvboxSource = "https://raw.githubusercontent.com/morhetz/gruvbox/master/colors/gruvbox.vim"
const tokyoNightSource = "https://github.com/folke/tokyonight.nvim"

export const ayuDark = makeTheme({
  id: "ayu-dark",
  name: "Ayu Dark",
  family: "Ayu",
  scheme: "dark",
  sourceName: "ayu-theme/ayu-colors",
  sourceUrl: ayuSource,
  license: "MIT",
  colors: paletteColors({
    bg: "#0a0e14",
    panel: "#0f1419",
    panelRaised: "#14191f",
    text: "#b3b1ad",
    textMuted: "#5c6773",
    accent: "#ffb454",
    hover: "#1f2430",
    selection: "#253340",
    border: "#1f2430",
    error: "#f07178",
    warning: "#ffb454",
    success: "#aad94c",
  }),
  highlights: paletteHighlights({
    keyword: "#ff8f40",
    function: "#ffb454",
    type: "#59c2ff",
    string: "#aad94c",
    number: "#d2a6ff",
    comment: "#5c6773",
    operator: "#f29668",
    variable: "#b3b1ad",
    attribute: "#ffd173",
    constant: "#d2a6ff",
    field: "#73d0ff",
    module: "#95e6cb",
  }),
  terminalAnsi: paletteAnsi({
    black: "#01060e",
    red: "#ea6c73",
    green: "#91b362",
    yellow: "#f9af4f",
    blue: "#53bdfa",
    magenta: "#fae994",
    cyan: "#90e1c6",
    white: "#c7c7c7",
    brightBlack: "#686868",
    brightRed: "#f07178",
    brightGreen: "#c2d94c",
    brightYellow: "#ffb454",
    brightBlue: "#59c2ff",
    brightMagenta: "#ffee99",
    brightCyan: "#95e6cb",
    brightWhite: "#ffffff",
  }),
})

export const ayuLight = makeTheme({
  id: "ayu-light",
  name: "Ayu Light",
  family: "Ayu",
  scheme: "light",
  sourceName: "ayu-theme/ayu-colors",
  sourceUrl: ayuSource,
  license: "MIT",
  colors: paletteColors({
    bg: "#fafafa",
    panel: "#f3f4f5",
    panelRaised: "#ffffff",
    text: "#5c6166",
    textMuted: "#8a9199",
    accent: "#ff9940",
    hover: "#e7eaed",
    selection: "#d1e4ff",
    border: "#d8dfe6",
    error: "#f51818",
    warning: "#ff9940",
    success: "#86b300",
  }),
  highlights: paletteHighlights({
    keyword: "#fa8d3e",
    function: "#f2ae49",
    type: "#55b4d4",
    string: "#86b300",
    number: "#a37acc",
    comment: "#abb0b6",
    operator: "#ed9366",
    variable: "#5c6166",
    attribute: "#f2ae49",
    constant: "#a37acc",
    field: "#55b4d4",
    module: "#4cbf99",
  }),
  terminalAnsi: paletteAnsi({
    black: "#000000",
    red: "#f51818",
    green: "#86b300",
    yellow: "#ff9940",
    blue: "#399ee6",
    magenta: "#a37acc",
    cyan: "#4cbf99",
    white: "#bfbfbf",
    brightBlack: "#686868",
    brightRed: "#ff3333",
    brightGreen: "#9acc00",
    brightYellow: "#ffaa33",
    brightBlue: "#55b4d4",
    brightMagenta: "#b294bb",
    brightCyan: "#6cc4a3",
    brightWhite: "#ffffff",
  }),
})

export const everforestDark = makeTheme({
  id: "everforest-dark",
  name: "Everforest Dark",
  family: "Everforest",
  scheme: "dark",
  sourceName: "sainnhe/everforest medium",
  sourceUrl: everforestSource,
  license: "MIT",
  colors: paletteColors({
    bg: "#2d353b",
    panel: "#232a2e",
    panelRaised: "#343f44",
    text: "#d3c6aa",
    textMuted: "#859289",
    accent: "#a7c080",
    hover: "#3d484d",
    selection: "#4f585e",
    border: "#475258",
    error: "#e67e80",
    warning: "#dbbc7f",
    success: "#a7c080",
  }),
  highlights: paletteHighlights({
    keyword: "#e67e80",
    function: "#a7c080",
    type: "#7fbbb3",
    string: "#a7c080",
    number: "#d699b6",
    comment: "#859289",
    operator: "#d3c6aa",
    variable: "#d3c6aa",
    attribute: "#dbbc7f",
    constant: "#d699b6",
    field: "#83c092",
    module: "#7fbbb3",
  }),
  terminalAnsi: paletteAnsi({
    black: "#475258",
    red: "#e67e80",
    green: "#a7c080",
    yellow: "#dbbc7f",
    blue: "#7fbbb3",
    magenta: "#d699b6",
    cyan: "#83c092",
    white: "#d3c6aa",
    brightBlack: "#859289",
    brightRed: "#e67e80",
    brightGreen: "#a7c080",
    brightYellow: "#dbbc7f",
    brightBlue: "#7fbbb3",
    brightMagenta: "#d699b6",
    brightCyan: "#83c092",
    brightWhite: "#fff9e8",
  }),
})

export const everforestLight = makeTheme({
  id: "everforest-light",
  name: "Everforest Light",
  family: "Everforest",
  scheme: "light",
  sourceName: "sainnhe/everforest medium",
  sourceUrl: everforestSource,
  license: "MIT",
  colors: paletteColors({
    bg: "#fdf6e3",
    panel: "#efebd4",
    panelRaised: "#fff9e8",
    text: "#5c6a72",
    textMuted: "#829181",
    accent: "#dfa000",
    hover: "#f4f0d9",
    selection: "#e0dcc7",
    border: "#d8d3ba",
    error: "#f85552",
    warning: "#dfa000",
    success: "#8da101",
  }),
  highlights: paletteHighlights({
    keyword: "#f85552",
    function: "#8da101",
    type: "#3a94c5",
    string: "#8da101",
    number: "#df69ba",
    comment: "#939f91",
    operator: "#5c6a72",
    variable: "#5c6a72",
    attribute: "#dfa000",
    constant: "#df69ba",
    field: "#35a77c",
    module: "#3a94c5",
  }),
  terminalAnsi: paletteAnsi({
    black: "#5c6a72",
    red: "#f85552",
    green: "#8da101",
    yellow: "#dfa000",
    blue: "#3a94c5",
    magenta: "#df69ba",
    cyan: "#35a77c",
    white: "#fdf6e3",
    brightBlack: "#829181",
    brightRed: "#f85552",
    brightGreen: "#93b259",
    brightYellow: "#dfa000",
    brightBlue: "#3a94c5",
    brightMagenta: "#df69ba",
    brightCyan: "#35a77c",
    brightWhite: "#fff9e8",
  }),
})

export const gruvboxDark = makeTheme({
  id: "gruvbox-dark",
  name: "Gruvbox Dark",
  family: "Gruvbox",
  scheme: "dark",
  sourceName: "morhetz/gruvbox",
  sourceUrl: gruvboxSource,
  license: "MIT",
  colors: paletteColors({
    bg: "#282828",
    panel: "#1d2021",
    panelRaised: "#3c3836",
    text: "#ebdbb2",
    textMuted: "#928374",
    accent: "#fabd2f",
    hover: "#32302f",
    selection: "#504945",
    border: "#504945",
    error: "#fb4934",
    warning: "#fabd2f",
    success: "#b8bb26",
  }),
  highlights: paletteHighlights({
    keyword: "#fb4934",
    function: "#fabd2f",
    type: "#8ec07c",
    string: "#b8bb26",
    number: "#d3869b",
    comment: "#928374",
    operator: "#ebdbb2",
    variable: "#ebdbb2",
    attribute: "#fe8019",
    constant: "#d3869b",
    field: "#83a598",
    module: "#8ec07c",
  }),
  terminalAnsi: paletteAnsi({
    black: "#282828",
    red: "#cc241d",
    green: "#98971a",
    yellow: "#d79921",
    blue: "#458588",
    magenta: "#b16286",
    cyan: "#689d6a",
    white: "#a89984",
    brightBlack: "#928374",
    brightRed: "#fb4934",
    brightGreen: "#b8bb26",
    brightYellow: "#fabd2f",
    brightBlue: "#83a598",
    brightMagenta: "#d3869b",
    brightCyan: "#8ec07c",
    brightWhite: "#ebdbb2",
  }),
})

export const gruvboxLight = makeTheme({
  id: "gruvbox-light",
  name: "Gruvbox Light",
  family: "Gruvbox",
  scheme: "light",
  sourceName: "morhetz/gruvbox",
  sourceUrl: gruvboxSource,
  license: "MIT",
  colors: paletteColors({
    bg: "#fbf1c7",
    panel: "#f2e5bc",
    panelRaised: "#f9f5d7",
    text: "#3c3836",
    textMuted: "#7c6f64",
    accent: "#b57614",
    hover: "#ebdbb2",
    selection: "#d5c4a1",
    border: "#d5c4a1",
    error: "#9d0006",
    warning: "#b57614",
    success: "#79740e",
  }),
  highlights: paletteHighlights({
    keyword: "#9d0006",
    function: "#b57614",
    type: "#427b58",
    string: "#79740e",
    number: "#8f3f71",
    comment: "#928374",
    operator: "#3c3836",
    variable: "#3c3836",
    attribute: "#af3a03",
    constant: "#8f3f71",
    field: "#076678",
    module: "#427b58",
  }),
  terminalAnsi: paletteAnsi({
    black: "#fbf1c7",
    red: "#cc241d",
    green: "#98971a",
    yellow: "#d79921",
    blue: "#458588",
    magenta: "#b16286",
    cyan: "#689d6a",
    white: "#7c6f64",
    brightBlack: "#928374",
    brightRed: "#9d0006",
    brightGreen: "#79740e",
    brightYellow: "#b57614",
    brightBlue: "#076678",
    brightMagenta: "#8f3f71",
    brightCyan: "#427b58",
    brightWhite: "#3c3836",
  }),
})

export const tokyoNightDark = makeTheme({
  id: "tokyonight-dark",
  name: "TokyoNight Dark",
  family: "TokyoNight",
  scheme: "dark",
  sourceName: "folke/tokyonight.nvim night",
  sourceUrl: tokyoNightSource,
  license: "Apache-2.0",
  colors: paletteColors({
    bg: "#1a1b26",
    panel: "#16161e",
    panelRaised: "#24283b",
    text: "#c0caf5",
    textMuted: "#565f89",
    accent: "#7aa2f7",
    hover: "#292e42",
    selection: "#33467c",
    border: "#2f3549",
    error: "#f7768e",
    warning: "#e0af68",
    success: "#9ece6a",
  }),
  highlights: paletteHighlights({
    keyword: "#bb9af7",
    function: "#7aa2f7",
    type: "#2ac3de",
    string: "#9ece6a",
    number: "#ff9e64",
    comment: "#565f89",
    operator: "#89ddff",
    variable: "#c0caf5",
    attribute: "#e0af68",
    constant: "#ff9e64",
    field: "#73daca",
    module: "#7dcfff",
  }),
  terminalAnsi: paletteAnsi({
    black: "#15161e",
    red: "#f7768e",
    green: "#9ece6a",
    yellow: "#e0af68",
    blue: "#7aa2f7",
    magenta: "#bb9af7",
    cyan: "#7dcfff",
    white: "#a9b1d6",
    brightBlack: "#414868",
    brightRed: "#f7768e",
    brightGreen: "#9ece6a",
    brightYellow: "#e0af68",
    brightBlue: "#7aa2f7",
    brightMagenta: "#bb9af7",
    brightCyan: "#7dcfff",
    brightWhite: "#c0caf5",
  }),
})

export const tokyoNightLight = makeTheme({
  id: "tokyonight-light",
  name: "TokyoNight Light",
  family: "TokyoNight",
  scheme: "light",
  sourceName: "folke/tokyonight.nvim day",
  sourceUrl: tokyoNightSource,
  license: "Apache-2.0",
  colors: paletteColors({
    bg: "#e1e2e7",
    panel: "#d5d6db",
    panelRaised: "#f1f2f7",
    text: "#3760bf",
    textMuted: "#6172b0",
    accent: "#2e7de9",
    hover: "#c4c8da",
    selection: "#b7c1e3",
    border: "#b7c1e3",
    error: "#f52a65",
    warning: "#8c6c3e",
    success: "#587539",
  }),
  highlights: paletteHighlights({
    keyword: "#7847bd",
    function: "#2e7de9",
    type: "#007197",
    string: "#587539",
    number: "#965027",
    comment: "#848cb5",
    operator: "#007197",
    variable: "#3760bf",
    attribute: "#8c6c3e",
    constant: "#965027",
    field: "#007197",
    module: "#2e7de9",
  }),
  terminalAnsi: paletteAnsi({
    black: "#e1e2e7",
    red: "#f52a65",
    green: "#587539",
    yellow: "#8c6c3e",
    blue: "#2e7de9",
    magenta: "#7847bd",
    cyan: "#007197",
    white: "#6172b0",
    brightBlack: "#a1a6c5",
    brightRed: "#f52a65",
    brightGreen: "#587539",
    brightYellow: "#8c6c3e",
    brightBlue: "#2e7de9",
    brightMagenta: "#7847bd",
    brightCyan: "#007197",
    brightWhite: "#3760bf",
  }),
})

const paletteThemes: Record<string, GharargahTheme> = {
  [ayuDark.id]: ayuDark,
  [ayuLight.id]: ayuLight,
  [everforestDark.id]: everforestDark,
  [everforestLight.id]: everforestLight,
  [gruvboxDark.id]: gruvboxDark,
  [gruvboxLight.id]: gruvboxLight,
  [tokyoNightDark.id]: tokyoNightDark,
  [tokyoNightLight.id]: tokyoNightLight,
}

export const bundledThemes: Record<string, GharargahTheme> = {
  ...paletteThemes,
  ...radDebuggerThemes,
  ...glassThemes,
}

export const bundledThemeList: GharargahTheme[] = [
  ...Object.values(paletteThemes),
  ...radDebuggerThemeList,
  ...glassThemeList,
]
export const defaultDark = ayuDark
export const defaultLight = ayuLight

export function getThemeById(id: string | null | undefined): GharargahTheme {
  if (!id) return ayuDark
  return bundledThemes[id] ?? ayuDark
}

export function themePreviewSwatches(theme: GharargahTheme): string[] {
  return theme.previewSwatches?.length ? theme.previewSwatches : [
    theme.colors.bg,
    theme.colors.panel,
    theme.colors.text,
    theme.colors.accent,
  ]
}

export function defaultThemeIdForScheme(scheme: ColorScheme): string {
  return scheme === "light" ? ayuLight.id : ayuDark.id
}

export function themeForScheme(scheme: ColorScheme): GharargahTheme {
  return getThemeById(defaultThemeIdForScheme(scheme))
}

export function themeFamilyForId(id: string | null | undefined): string {
  return getThemeById(id).family ?? "Ayu"
}

export function siblingThemeForScheme(id: string, scheme: ColorScheme): GharargahTheme {
  const current = getThemeById(id)
  const family = current.family
  const match = bundledThemeList.find(theme => theme.family === family && theme.scheme === scheme)
  return match ?? themeForScheme(scheme)
}
