import {
  makeTheme,
  paletteAnsi,
  paletteColors,
  paletteHighlights,
} from "./theme-palette.js"

/** Original Gharargah glass sci-fi home accents — monochromatic dark variants. */
const glassSource = "https://github.com/amirrezaask/jet"

export const glassBlue = makeTheme({
  id: "glass-blue",
  name: "Glass Blue",
  family: "Glass",
  scheme: "dark",
  sourceName: "Gharargah Glass",
  sourceUrl: glassSource,
  license: "MIT",
  colors: paletteColors({
    bg: "#05070c",
    panel: "#0a1018",
    panelRaised: "#0e1622",
    text: "#d8e6f7",
    textMuted: "#6b8499",
    accent: "#4db8ff",
    hover: "#121c2c",
    selection: "#1a2a42",
    border: "#1a2a3d",
    focusBorder: "#6ec8ff",
    error: "#ff6b7a",
    warning: "#7ec8ff",
    success: "#5ce1ff",
  }),
  highlights: paletteHighlights({
    keyword: "#6ec8ff",
    controlKeyword: "#4db8ff",
    function: "#9ad4ff",
    type: "#7ec8ff",
    string: "#5ce1ff",
    number: "#b8dcff",
    comment: "#4a6278",
    operator: "#8ec8ef",
    variable: "#d8e6f7",
    attribute: "#9ad4ff",
    constant: "#7ec8ff",
    field: "#8ec8ef",
    module: "#5ce1ff",
  }),
  terminalAnsi: paletteAnsi({
    black: "#05070c",
    red: "#ff6b7a",
    green: "#5ce1ff",
    yellow: "#9ad4ff",
    blue: "#4db8ff",
    magenta: "#7ec8ff",
    cyan: "#5ce1ff",
    white: "#d8e6f7",
    brightBlack: "#4a6278",
    brightRed: "#ff8a96",
    brightGreen: "#8aefff",
    brightYellow: "#c0e4ff",
    brightBlue: "#6ec8ff",
    brightMagenta: "#9ad4ff",
    brightCyan: "#8aefff",
    brightWhite: "#ffffff",
  }),
})

export const glassRed = makeTheme({
  id: "glass-red",
  name: "Glass Red",
  family: "Glass",
  scheme: "dark",
  sourceName: "Gharargah Glass",
  sourceUrl: glassSource,
  license: "MIT",
  colors: paletteColors({
    bg: "#0a0506",
    panel: "#14090a",
    panelRaised: "#1a0c0e",
    text: "#f5e4e6",
    textMuted: "#9a6b70",
    accent: "#ff3b4a",
    hover: "#2a1216",
    selection: "#3a1820",
    border: "#3a1a20",
    focusBorder: "#ff6b76",
    error: "#ff5a68",
    warning: "#ff8a70",
    success: "#ff6b76",
  }),
  highlights: paletteHighlights({
    keyword: "#ff6b76",
    controlKeyword: "#ff3b4a",
    function: "#ff8a96",
    type: "#ff7a84",
    string: "#ff9aa2",
    number: "#ffb0b6",
    comment: "#6a4048",
    operator: "#ff8a90",
    variable: "#f5e4e6",
    attribute: "#ff8a96",
    constant: "#ff7a84",
    field: "#ff8a90",
    module: "#ff9aa2",
  }),
  terminalAnsi: paletteAnsi({
    black: "#0a0506",
    red: "#ff3b4a",
    green: "#ff8a70",
    yellow: "#ffb0a0",
    blue: "#ff6b76",
    magenta: "#ff5a90",
    cyan: "#ff9aa2",
    white: "#f5e4e6",
    brightBlack: "#6a4048",
    brightRed: "#ff6b76",
    brightGreen: "#ffb090",
    brightYellow: "#ffc8b8",
    brightBlue: "#ff8a96",
    brightMagenta: "#ff7aa0",
    brightCyan: "#ffb0b6",
    brightWhite: "#ffffff",
  }),
})

export const glassGreen = makeTheme({
  id: "glass-green",
  name: "Glass Green",
  family: "Glass",
  scheme: "dark",
  sourceName: "Gharargah Glass",
  sourceUrl: glassSource,
  license: "MIT",
  colors: paletteColors({
    bg: "#050a07",
    panel: "#0a140e",
    panelRaised: "#0e1a12",
    text: "#d4f5e4",
    textMuted: "#5a8a6e",
    accent: "#3dff9a",
    hover: "#122a1a",
    selection: "#1a3a28",
    border: "#1a3a28",
    focusBorder: "#6effb4",
    error: "#ff6b7a",
    warning: "#b8ff6e",
    success: "#3dff9a",
  }),
  highlights: paletteHighlights({
    keyword: "#6effb4",
    controlKeyword: "#3dff9a",
    function: "#8affc4",
    type: "#5cefa8",
    string: "#a0ffd0",
    number: "#c0ffe0",
    comment: "#3a6a50",
    operator: "#7aefb0",
    variable: "#d4f5e4",
    attribute: "#8affc4",
    constant: "#5cefa8",
    field: "#7aefb0",
    module: "#a0ffd0",
  }),
  terminalAnsi: paletteAnsi({
    black: "#050a07",
    red: "#ff6b7a",
    green: "#3dff9a",
    yellow: "#b8ff6e",
    blue: "#5cefa8",
    magenta: "#8affc4",
    cyan: "#6effb4",
    white: "#d4f5e4",
    brightBlack: "#3a6a50",
    brightRed: "#ff8a96",
    brightGreen: "#6effb4",
    brightYellow: "#d0ff90",
    brightBlue: "#8affc4",
    brightMagenta: "#a0ffd0",
    brightCyan: "#8affc4",
    brightWhite: "#ffffff",
  }),
})

export const glassThemes = {
  [glassBlue.id]: glassBlue,
  [glassRed.id]: glassRed,
  [glassGreen.id]: glassGreen,
}

export const glassThemeList = [glassBlue, glassRed, glassGreen]
